package com.example.zuerijoeppli.theme

import androidx.compose.ui.graphics.Color

// Brand
val EcoGreen = Color(0xFF6DBA32)
val ZurichBlue = Color(0xFF3247BA)
val LightGrey = Color(0xFFF8F9FA)
val PureWhite = Color(0xFFFFFFFF)
val DarkSlate = Color(0xFF1A1C1E)
val TwintCyan = Color(0xFF00B5E2)

val EcoGreenDark = Color(0xFF5AA328)
val ZurichBlueDark = Color(0xFF1A256B)
val LightGreyDark = Color(0xFF121212)
val SurfaceDark = Color(0xFF1E1E1E)

// --- Material 3 roles, light ---
val PrimaryContainerLight = Color(0xFFD7F5C2)
val OnPrimaryContainerLight = Color(0xFF133800)
val SecondaryContainerLight = Color(0xFFDDE1FF)
val OnSecondaryContainerLight = Color(0xFF001454)
val TertiaryLight = Color(0xFFFFCB00)
val OnTertiaryLight = Color(0xFF3A2E00)
val TertiaryContainerLight = Color(0xFFFFE08A)
val OnTertiaryContainerLight = Color(0xFF261A00)
val ErrorLight = Color(0xFFBA1A1A)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val OnSurfaceVariantLight = Color(0xFF5C5E66)
val SurfaceVariantLight = Color(0xFFEDEDED)
val OutlineLight = Color(0xFF73796E)
val OutlineVariantLight = Color(0xFFE3E4E1)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFFFFFFF)
val SurfaceContainerLight = Color(0xFFF1F2EF)
val SurfaceContainerHighLight = Color(0xFFEAEBE8)
val SurfaceContainerHighestLight = Color(0xFFE4E5E2)

// --- Material 3 roles, dark ---
val PrimaryDarkScheme = Color(0xFF93D656)
val OnPrimaryDarkScheme = Color(0xFF1C3700)
val PrimaryContainerDark = Color(0xFF2E5300)
val OnPrimaryContainerDark = Color(0xFFD7F5C2)
val SecondaryDarkScheme = Color(0xFFB7C4FF)
val OnSecondaryDarkScheme = Color(0xFF0E2090)
val SecondaryContainerDark = Color(0xFF2A3BA0)
val OnSecondaryContainerDark = Color(0xFFDDE1FF)
val TertiaryDark = Color(0xFFFFD630)
val OnTertiaryDark = Color(0xFF3A2E00)
val TertiaryContainerDark = Color(0xFF564500)
val OnTertiaryContainerDark = Color(0xFFFFE08A)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val OnSurfaceVariantDark = Color(0xFFC6C7CC)
val SurfaceVariantDark = Color(0xFF2A2B2E)
val OutlineDark = Color(0xFF909097)
val OutlineVariantDark = Color(0xFF3C3D42)
val SurfaceContainerLowestDark = Color(0xFF0E0E10)
val SurfaceContainerLowDark = Color(0xFF1B1B1E)
val SurfaceContainerDarkTone = Color(0xFF1F1F23)
val SurfaceContainerHighDark = Color(0xFF29292D)
val SurfaceContainerHighestDark = Color(0xFF343438)
