package com.example.zuerijoeppli.ui

import androidx.compose.runtime.staticCompositionLocalOf

data class JoeppliStrings(
    val appName: String,
    val greeting: String,
    val readyToRecycle: String,
    val statKarma: String,
    val statCo2: String,
    val quickPickup: String,
    val quickPickupDesc: String,
    val bottomStart: String,
    val bottomRecycling: String,
    val bottomScanner: String,
    val bottomProfile: String,
    val profileContact: String,
    val profileName: String,
    val profilePhone: String,
    val profileAddress: String,
    val profileSave: String,
    val profileSaveToast: String,
    val profilePayment: String,
    val profileSupportTitle: String,
    val profileSupportSubtitle: String,
    val profileSupportMsg: String,
    val profileSupportSend: String,
    val profileSupportToast: String,
    val profileSupportError: String,
    val profileLogout: String,
    val profileLogoutToast: String,
    val profileLangTitle: String,
    val addressRegTitle: String,
    val addressRegSubtitle: String,
    val addressRegCustom: String,
    val addressRegQuick: String,
    val addressRegSubmit: String,
    val addressRegBack: String,
    val addressRegToast: String,
    val authSelectTitle: String,
    val authGoogleBtn: String,
    val authEmailBtn: String,
    val authPhoneBtn: String,
    val authBackBtn: String,
    val authGoogleHeader: String,
    val authGoogleSelect: String,
    val authEmailHeader: String,
    val authPhoneHeader: String,
    val authPhoneEnter: String,
    val authPhoneEnterPlaceholder: String,
    val authPhoneSendOtp: String,
    val authPhoneOtpEnter: String,
    val authPhoneOtpDesc: String,
    val authPhoneOtpVerify: String,
    val authPhoneOtpVerifyToast: String,
    val authEmailName: String,
    val authEmailNamePlaceholder: String,
    val authEmailMail: String,
    val authEmailPassword: String,
    val authEmailPasswordPlaceholder: String,
    val authEmailRegister: String,
    val authEmailErrorFill: String,
    val authPhoneErrorValid: String,
    val authPhoneErrorOtp: String,
    
    // Additional UI terms for Guide & Order screens
    val orderAddressTitle: String,
    val orderDateSlotTitle: String,
    val orderMaterialsTitle: String,
    val orderSummaryTitle: String,
    val orderPaymentTitle: String,
    val orderTrackerTitle: String,
    val orderNext: String,
    val orderBack: String,
    val orderStepAddress: String,
    val orderStepSlot: String,
    val orderStepMaterials: String,
    val orderStepSummary: String,
    val orderStepPayment: String,
    val orderStepTracker: String,
    val orderAddressPlaceholder: String,
    val orderExpressToggle: String,
    val orderExpressDesc: String,
    val orderSlotMorning: String,
    val orderSlotAfternoon: String,
    val orderSlotEvening: String,
    val orderBulkyWaste: String,
    val orderStandardWaste: String,
    val orderSummaryBulkyCount: String,
    val orderSummaryExpressFee: String,
    val orderSummaryTotal: String,
    val orderTwintPay: String,
    val orderTwintDemoSuccess: String,
    val orderTwintCancel: String,
    val orderTrackerStatus: String,
    val orderTrackerHardau: String,
    val orderTrackerHardbruecke: String,
    val orderTrackerArrived: String,
    val orderTrackerDone: String,
    val guideTitle: String,
    val guideSubtitle: String,
    val guideScannerTitle: String,
    val guideScannerSubtitle: String,
    val guideScannerPrompt: String,
    val guideScanButton: String,
    val guideScanResultTitle: String,
    val guideScanDetails: String,
    val guideCategoryAll: String,
    val guideSwipeAdd: String,
    val guideSwipeAddedToast: String
)

val EnStrings = JoeppliStrings(
    appName = "Züri-Jöppli",
    greeting = "Hello, %s!",
    readyToRecycle = "Ready to recycle?",
    statKarma = "Züri-Karma",
    statCo2 = "CO2 saved",
    quickPickup = "Quick Pickup",
    quickPickupDesc = "Collect my favorites",
    bottomStart = "Start",
    bottomRecycling = "Recycling",
    bottomScanner = "Scanner",
    bottomProfile = "Profile",
    profileContact = "Residence & Contact",
    profileName = "First & Last Name",
    profilePhone = "Phone Number",
    profileAddress = "Zürich Residence Address",
    profileSave = "Save Settings",
    profileSaveToast = "Profile settings saved successfully",
    profilePayment = "Default Payment Method",
    profileSupportTitle = "Contact ERZ Control Center",
    profileSupportSubtitle = "Questions about waste disposal or your Jöppli vehicle?",
    profileSupportMsg = "Your message",
    profileSupportSend = "Send Message",
    profileSupportToast = "Message sent! ERZ will respond shortly.",
    profileSupportError = "Please enter a message before sending",
    profileLogout = "Log Out",
    profileLogoutToast = "Successfully logged out",
    profileLangTitle = "Language / Sprache",
    addressRegTitle = "Register Address",
    addressRegSubtitle = "We need your Zürich home address so that our Jöppli vehicles can pick up recycling at your doorstep.",
    addressRegCustom = "Doorstep Pickup Address",
    addressRegQuick = "Quick Selection (Common Addresses)",
    addressRegSubmit = "Register Address",
    addressRegBack = "Log Out & Back",
    addressRegToast = "Address successfully registered!",
    authSelectTitle = "Select Login Method",
    authGoogleBtn = "Continue with Google",
    authEmailBtn = "Continue with Email",
    authPhoneBtn = "Continue with Phone Number",
    authBackBtn = "Back",
    authGoogleHeader = "Google Login",
    authGoogleSelect = "Choose a Google account:",
    authEmailHeader = "Email Sign-In",
    authPhoneHeader = "SMS Verification",
    authPhoneEnter = "Phone Number",
    authPhoneEnterPlaceholder = "e.g. +41 79 123 45 67",
    authPhoneSendOtp = "Send Verification Code",
    authPhoneOtpEnter = "SMS Code (6 digits)",
    authPhoneOtpDesc = "We sent a 6-digit verification code to %s. Enter it below.",
    authPhoneOtpVerify = "Verify Code",
    authPhoneOtpVerifyToast = "Verified successfully!",
    authEmailName = "Display Name",
    authEmailNamePlaceholder = "e.g. Ueli Maurer",
    authEmailMail = "Email Address",
    authEmailPassword = "Password",
    authEmailPasswordPlaceholder = "At least 6 characters",
    authEmailRegister = "Register & Log In",
    authEmailErrorFill = "Please fill in all fields correctly",
    authPhoneErrorValid = "Please enter a valid phone number",
    authPhoneErrorOtp = "Please enter the 6-digit code",
    
    orderAddressTitle = "Pickup Address",
    orderDateSlotTitle = "Date & Time Slot",
    orderMaterialsTitle = "Recycle Materials",
    orderSummaryTitle = "Surcharges Summary",
    orderPaymentTitle = "Payment Method",
    orderTrackerTitle = "Jöppli Live Tracker",
    orderNext = "Next Step",
    orderBack = "Back",
    orderStepAddress = "Address",
    orderStepSlot = "Time Slot",
    orderStepMaterials = "Materials",
    orderStepSummary = "Summary",
    orderStepPayment = "Payment",
    orderStepTracker = "Live Map",
    orderAddressPlaceholder = "Zürich address...",
    orderExpressToggle = "Express Summon Jöppli",
    orderExpressDesc = "Dispatches vehicle within 30 minutes (+CHF 4.50)",
    orderSlotMorning = "Morning (08:00 - 12:00)",
    orderSlotAfternoon = "Afternoon (13:00 - 17:00)",
    orderSlotEvening = "After-Hours (18:00 - 21:00)",
    orderBulkyWaste = "Bulky / Special Waste (Paid)",
    orderStandardWaste = "Standard Sorting Materials (Free)",
    orderSummaryBulkyCount = "Bulky waste items",
    orderSummaryExpressFee = "Express dispatch surcharge",
    orderSummaryTotal = "Total Price",
    orderTwintPay = "Pay with TWINT",
    orderTwintDemoSuccess = "TWINT Payment Simulated Successfully!",
    orderTwintCancel = "Cancel Payment",
    orderTrackerStatus = "Jöppli Vehicle Status",
    orderTrackerHardau = "Departing ERZ Werkhof Hardau...",
    orderTrackerHardbruecke = "Driving across Hardbrücke...",
    orderTrackerArrived = "Arrived at your doorstep!",
    orderTrackerDone = "Recycling pickup completed!",
    guideTitle = "Recycling Guide",
    guideSubtitle = "Zürich waste index and scanner",
    guideScannerTitle = "AI Recycling Scanner",
    guideScannerSubtitle = "Hold an item to your camera to scan",
    guideScannerPrompt = "Select an item to simulate scanning with AI:",
    guideScanButton = "Scan Item",
    guideScanResultTitle = "AI Scan Analysis",
    guideScanDetails = "Details & Advice",
    guideCategoryAll = "All",
    guideSwipeAdd = "Swipe left to add to pickup",
    guideSwipeAddedToast = "%s added to Jöppli pickup!"
)

val DeStrings = JoeppliStrings(
    appName = "Züri-Jöppli",
    greeting = "Grüezi, %s!",
    readyToRecycle = "Parat zum recycle?",
    statKarma = "Züri-Karma",
    statCo2 = "CO2 gspart",
    quickPickup = "Schnäll Abholig",
    quickPickupDesc = "Hole mini Favorite",
    bottomStart = "Start",
    bottomRecycling = "Recycling",
    bottomScanner = "Scanner",
    bottomProfile = "Profil",
    profileContact = "Wohnort & Kontakt",
    profileName = "Vorname Nachname",
    profilePhone = "Telefonnummer",
    profileAddress = "Zürcher Wohnadresse",
    profileSave = "Spichere",
    profileSaveToast = "Date erfolgriich gspicheret",
    profilePayment = "Standard-Zahlmittel",
    profileSupportTitle = "ERZ Leitstell kontaktiere",
    profileSupportSubtitle = "Hesch Frage zur Entsorgig oder dim Jöppli-Fahrzüg?",
    profileSupportMsg = "Dini Mitteilig",
    profileSupportSend = "Nachricht absende",
    profileSupportToast = "Meldig gsendet! ERZ wird antworte.",
    profileSupportError = "Bitte Nachricht igäh",
    profileLogout = "Abmelde (Log Out)",
    profileLogoutToast = "Erfolgriich abgemeldet",
    profileLangTitle = "Sprache / Language",
    addressRegTitle = "Adresse registriere",
    addressRegSubtitle = "Damit mir d'Recycling-Entsorgig vor dinere Huustüre abhole chönne, bruche mir dini Zürcher Wohnadresse.",
    addressRegCustom = "Huustür Abholadresse",
    addressRegQuick = "Schnelluswahl (Häufigi Adresse)",
    addressRegSubmit = "Adresse registriere",
    addressRegBack = "Abmelde & Zrugg",
    addressRegToast = "Adresse gspicheret!",
    authSelectTitle = "Anmeldemethode wählen",
    authGoogleBtn = "Mit Google anmelden",
    authEmailBtn = "Mit E-Mail anmelden",
    authPhoneBtn = "Mit Telefonnummer anmelden",
    authBackBtn = "Zurück",
    authGoogleHeader = "Google Anmeldung",
    authGoogleSelect = "Wähle ein Google-Konto aus:",
    authEmailHeader = "E-Mail Login",
    authPhoneHeader = "SMS-Verifikation",
    authPhoneEnter = "Telefonnummer",
    authPhoneEnterPlaceholder = "e.g. +41 79 123 45 67",
    authPhoneSendOtp = "Sende Verifikations-Code",
    authPhoneOtpEnter = "SMS-Code (6 Ziffern)",
    authPhoneOtpDesc = "Wir haben einen 6-stelligen Code an %s gesendet. Trage ihn unten ein.",
    authPhoneOtpVerify = "Code verifizieren",
    authPhoneOtpVerifyToast = "Verifiziert!",
    authEmailName = "Displays Name",
    authEmailNamePlaceholder = "z.B. Ueli Maurer",
    authEmailMail = "E-Mail Adresse",
    authEmailPassword = "Passwort",
    authEmailPasswordPlaceholder = "Mindestens 6 Zeichen",
    authEmailRegister = "Registrieren & Anmelden",
    authEmailErrorFill = "Bitte fülle alle Felder korrekt aus",
    authPhoneErrorValid = "Bitte gib eine gültige Telefonnummer ein",
    authPhoneErrorOtp = "Bitte gib den 6-stelligen Code ein",
    
    orderAddressTitle = "Abholadresse",
    orderDateSlotTitle = "Datum & Zeitfenster",
    orderMaterialsTitle = "Recycling-Materialien",
    orderSummaryTitle = "Zuschläge Übersicht",
    orderPaymentTitle = "Zahlungsmethode",
    orderTrackerTitle = "Jöppli Live Tracker",
    orderNext = "Nächste Schritt",
    orderBack = "Zurück",
    orderStepAddress = "Adresse",
    orderStepSlot = "Zeitfenster",
    orderStepMaterials = "Materialien",
    orderStepSummary = "Übersicht",
    orderStepPayment = "Zahlung",
    orderStepTracker = "Live-Karte",
    orderAddressPlaceholder = "Zürcher Adresse...",
    orderExpressToggle = "Express Jöppli bestellen",
    orderExpressDesc = "Fahrzeug fährt innerhalb von 30 Min. ab (+CHF 4.50)",
    orderSlotMorning = "Vormittag (08:00 - 12:00)",
    orderSlotAfternoon = "Nachmittag (13:00 - 17:00)",
    orderSlotEvening = "Feierabend (18:00 - 21:00)",
    orderBulkyWaste = "Sperrgut / Sonderabfall (Kostenpflichtig)",
    orderStandardWaste = "Standard Recycling-Abfälle (Kostenlos)",
    orderSummaryBulkyCount = "Sperrgut-Gegenstände",
    orderSummaryExpressFee = "Express-Abholungsgebühr",
    orderSummaryTotal = "Gesamtpreis",
    orderTwintPay = "Mit TWINT bezahlen",
    orderTwintDemoSuccess = "TWINT Zahlung erfolgreich simuliert!",
    orderTwintCancel = "Zahlung abbrechen",
    orderTrackerStatus = "Jöppli Fahrzeugstatus",
    orderTrackerHardau = "Fährt vom ERZ Werkhof Hardau ab...",
    orderTrackerHardbruecke = "Fährt über die Hardbrücke...",
    orderTrackerArrived = "Vor deiner Haustüre angekommen!",
    orderTrackerDone = "Recycling-Abholung beendet!",
    guideTitle = "Recycling-Leitfaden",
    guideSubtitle = "Zürcher Abfallverzeichnis und Scanner",
    guideScannerTitle = "AI Recycling-Scanner",
    guideScannerSubtitle = "Halte ein Objekt in die Kamera zum Scannen",
    guideScannerPrompt = "Wähle ein Objekt zum AI-Scan simulieren:",
    guideScanButton = "Objekt scannen",
    guideScanResultTitle = "AI-Scananalyse",
    guideScanDetails = "Details & Entsorgungstipps",
    guideCategoryAll = "Alle",
    guideSwipeAdd = "Nach links wischen zum Hinzufügen",
    guideSwipeAddedToast = "%s zum Jöppli hinzugefügt!"
)

val LocalJoeppliStrings = staticCompositionLocalOf { DeStrings }
